{576}
FloorPlanScreen*
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[1]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[1]
	[Open\Drawer]
	[6]
	[Get\Check]
InputDialog
	"Enter Guest Count"
	"1"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{575}
FloorPlanScreen
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[1]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[1]
	[Open\Drawer]
	[6]
	[Get\Check]
{558}
FloorPlanScreen
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[3]
	[Open\Drawer]
	[6]
	[Get\Check]
{412}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
	"test"
Items
	" Large"
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{408}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" Beef"
	" Beef"
	" 1/2"
	" Chicken"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{407}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" Beef"
	" Beef"
	" 1/2"
	" Chicken"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You may not have more than 3 items from the Pizza Toppings group."
	[X]
	[OK]
{406}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" Beef"
	" Beef"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{402}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{401}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Large"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{400}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{399}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" 1/2"
	" Chicken"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{398}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{397}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{396}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" Large"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{395}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
Items
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{344}
TenderScreen
TopRightButtons
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
TopLeftButtons
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
ItemEntries
*
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
	"HIGH LIFE"
	"2.00"
Promos
Comps
	"Sub Total"
	"10.00"
Taxes
	"Tax"
	"0.00"
	"Total"
	"10.00"
Tenders
	"CASH"
	"10.00"
	"Change"
	"$0.00"
MidButtons
	[Gift Card Balance]
	[Close]
MidLeftButtons
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
BottomRightButtons
BottomLeftButtons
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
WarningBarControl
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
{343}
TenderScreen
TopRightButtons
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
TopLeftButtons
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
ItemEntries
*
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
	"HIGH LIFE"
	"2.00"
Promos
Comps
	"Sub Total"
	"10.00"
Taxes
	"Tax"
	"0.00"
	"Total"
	"10.00"
Tenders
	"Balance Due"
	"$10.00"
MidButtons
	[Gift Card Balance]
	[Close*]
MidLeftButtons
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
BottomRightButtons
BottomLeftButtons
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
WarningBarControl
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
{341}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
	"HIGH LIFE"
	"2.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
MenuOrModButtons
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{340}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
MenuOrModButtons
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{339}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
MenuOrModButtons
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{338}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"MILLER LITE"
	"3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
MenuOrModButtons
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{337}
TenderScreen
TopRightButtons
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
TopLeftButtons
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
ItemEntries
*
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
	"CALI CHIX WRAP\ FRIES"
	"4.00"
Promos
Comps
	"Sub Total"
	"20.00"
Taxes
	"Tax"
	"1.22"
	"Total"
	"21.22"
Tenders
	"CASH"
	"21.22"
	"Change"
	"$0.00"
MidButtons
	[Gift Card Balance]
	[Close]
MidLeftButtons
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
BottomRightButtons
BottomLeftButtons
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
WarningBarControl
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
{319}
TenderScreen
TopRightButtons
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
TopLeftButtons
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
ItemEntries
*
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
	"CALI CHIX WRAP\ FRIES"
	"4.00"
Promos
Comps
	"Sub Total"
	"20.00"
Taxes
	"Tax"
	"1.22"
	"Total"
	"21.22"
Tenders
	"Balance Due"
	"$21.22"
MidButtons
	[Gift Card Balance]
	[Close*]
MidLeftButtons
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
BottomRightButtons
BottomLeftButtons
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
WarningBarControl
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
{310}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	"0"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
GetCheckDialog
TopCancelOkButtons
	[btnClose]
	"Get Tab"
	[btnOk]
TopGetButtons
	[Get Table]
	[Get Tab]
	[Get Check]
	??
Keyboard
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
{307}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	"0"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
GetCheckDialog
TopCancelOkButtons
	[btnClose]
	"Get Table"
	[btnOk]
TopGetButtons
	[Get Table]
	[Get Tab]
	[Get Check]
	??
Keyboard
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
{306}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
GetCheckDialog
TopCancelOkButtons
	[btnClose]
	"Get Table"
	[btnOk]
TopGetButtons
	[Get Table]
	[Get Tab]
	[Get Check]
	??
Keyboard
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
{298}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{297}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
	"Seat 2"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{294}
SplitSeatScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"For Table"
CheckOrSeat
	"Seat 1"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
CheckOrSeat
	"Seat 2"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split check]
	[Close]
{284}
SplitSeatScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"For Table"
CheckOrSeat
	"Seat 1"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split check]
	[Close]
{275}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{274}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" Chicken"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{273}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
	"CALI CHIX WRAP\ FRIES"
	"4.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{272}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You are required to enter between 1 and 3 item(s) from the Pizza Toppings mod group."
	[X]
	[OK]
{271}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{270}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{269}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
	"CHIX SLD SAND\ FRIES"
	"4.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{268}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
Items
	" Large"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{265}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
Items
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{264}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Large"
	" Sausage"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You are required to enter exactly 1 item(s) from the Pizza Crust mod group."
	[X]
	[OK]
{260}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{258}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Large"
	" Sausage"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{256}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{251}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{244}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CARROT CAKE"
	"2.50"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{243}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{229}
TenderScreen
TopRightButtons
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
TopLeftButtons
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
ItemEntries
*
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
	"CHEESECAKE"
	"2.50"
Promos
Comps
	"Sub Total"
	"7.50"
Taxes
	"Tax"
	"0.46"
	"Total"
	"7.96"
Tenders
	"CASH"
	"7.96"
	"Change"
	"$0.00"
MidButtons
	[Gift Card Balance]
	[Close]
MidLeftButtons
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
BottomRightButtons
BottomLeftButtons
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
WarningBarControl
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
{216}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{204}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{189}
TenderScreen
TopRightButtons
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
TopLeftButtons
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
ItemEntries
*
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
	"CHEESECAKE"
	"2.50"
Promos
Comps
	"Sub Total"
	"7.50"
Taxes
	"Tax"
	"0.46"
	"Total"
	"7.96"
Tenders
	"Balance Due"
	"$7.96"
MidButtons
	[Gift Card Balance]
	[Close*]
MidLeftButtons
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
BottomRightButtons
BottomLeftButtons
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
WarningBarControl
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
{185}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" CHEDDAR"
	" 1/2"
CenterModButtons
	[CHEDDAR]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{183}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" CHEDDAR"
	" 1/2"
CenterModButtons
	[CHEDDAR]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You may not have more than 1 items from the CHEESE group."
	[X]
	[OK]
{174}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" 1/2"
	" 1/2"
CenterModButtons
	[CHEDDAR]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{170}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" 1/2"
	" 1/2"
CenterModButtons
	[VEGGIE]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{163}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" 1/2"
	" 1/2"
CenterModButtons
	[VEGGIE]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You may not have more than 1 items from the QUICHE group."
	[X]
	[OK]
{161}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" 1/2"
	" 1/2"
CenterModButtons
	[VEGGIE]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{158}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{157}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You may not have more than 3 items from the Pizza Toppings group."
	[X]
	[OK]
{156}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{155}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
	"CHEESECAKE"
	"2.50"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{152}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" Large"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{151}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
Items
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{145}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" Beef"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{144}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" Beef"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
MessageDialog
	"Warning"
DialogSeparator
	"You may not have more than 3 items from the Pizza Toppings group."
	[X]
	[OK]
{140}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{131}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{105}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
MenuOrModButtons
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{099}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
	"CHICKEN CAESAR"
	"3.00"
	"SOUP OF DAY\ CUP"
	"3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{096}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"H COKE"
	"2.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
	[BEER]
MenuOrModButtons
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
BottomButtons
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	[Hold]
	[Recipe]
{094}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
	"CHICKEN CAESAR"
	"3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{093}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	"0"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{086}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{083}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{082}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{081}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{080}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{079}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{072}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"Table 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
	"Seat 1"
	"COKE"
	"2.00"
Seats
	[T]
	[1]
	[>]
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
	[BEER]
MenuOrModButtons
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
BottomButtons
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	[Hold]
	[Recipe]
HoldItemsDialog
	[btnCancel]
	"1 mins"
	[btnOk]
MinusPlusButtons
	[-]
ctrlSlider_Container
ctrlSlider
	[+]
Plus5And10Buttons
	[+5]
	[+10]
OrderModeButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
	[Happy hour]
{067}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"WATER"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"COKE"
CheckOrSeat
	"Check 3"
Entries
	"Seat 3"
	"DIET COKE"
CheckOrSeat
	"Check 4"
Entries
	"Seat 4"
	"DIET 7UP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{066}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 5"
Entries
	"Seat 5"
	"ICED TEA"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{065}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"WATER"
	"Seat 5"
	"ICED TEA"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"COKE"
CheckOrSeat
	"Check 3"
Entries
	"Seat 3"
	"DIET COKE"
CheckOrSeat
	"Check 4"
Entries
	"Seat 4"
	"DIET 7UP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{064}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"WATER"
	"Seat 4"
	"DIET 7UP"
	"Seat 5"
	"ICED TEA"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"COKE"
CheckOrSeat
	"Check 3"
Entries
	"Seat 3"
	"DIET COKE"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{063}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"WATER"
	"Seat 3"
	"DIET COKE"
	"Seat 4"
	"DIET 7UP"
	"Seat 5"
	"ICED TEA"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"COKE"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{062}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"WATER"
	"Seat 2"
	"COKE"
	"Seat 3"
	"DIET COKE"
	"Seat 4"
	"DIET 7UP"
	"Seat 5"
	"ICED TEA"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{061}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{060}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
	"Seat 2"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{059}
SplitSeatScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"For Table"
CheckOrSeat
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
CheckOrSeat
	"Seat 2"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split check]
	[Close]
{058}
SplitSeatScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"For Table"
CheckOrSeat
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split check]
	[Close]
{057}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"COKE"
CheckOrSeat
	"Check 2"
Entries
	"Seat 2"
	"7 UP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{056}
SplitCheckScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"Check 1"
Entries
	"Seat 1"
	"COKE"
	"Seat 2"
	"7 UP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split seat]
	[Close]
{055}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTabNameKeyboard
	?j1?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
InputDialog
	"Enter Guest Count"
	"1"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{054}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"j1"
	"List of existing owned tables"
ExistingTables
	"2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
InputDialog
	"Enter table name"
	"0"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{053}
OrderScreen
TopLeftButtons
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat*]
	[Done]
TopRightButtons
	[HERE]
	[TO GO]
	[DON'T MAKE]
TableAndChecks
	"SJ 1"
	[Clear]
	[Check 1]
	[+]
EntriesBySeat
*
CenterMenuButtons
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
MenuOrModButtons
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
BottomButtons
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
{051}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
	"List of existing owned tables"
ExistingTables
	"2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
KeyboardEntryDialog
	"Enter tab name"
	""
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
{050}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"j1"
	"List of existing owned tabs"
ExistingTables
	"j1"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{049}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j1"
	[btnSetTableEntry]
Tables
	"2"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{047}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
	"List of existing owned tabs"
ExistingTables
	"j1"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{046}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j1"
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{045}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTabNameKeyboard
	?j1?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
InputDialog
	"Enter Guest Count"
	"1"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{044}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTabNameKeyboard
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
{042}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"j1"
	"List of existing owned tabs"
ExistingTables
	"j2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
KeyboardEntryDialog
	"Enter tab name"
	""
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
{041}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
	"List of existing owned tabs"
ExistingTables
	"j2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
InputDialog
	"Enter table name"
	"0"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{040}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
	"List of existing owned tabs"
ExistingTables
	"j2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{039}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j2"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{037}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"j1"
	"List of existing owned tabs"
ExistingTables
	"j2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{033}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"j1"
	"List of existing owned tables"
ExistingTables
	"2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{031}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j1"
	"j2"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{030}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j1"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTabNameKeyboard
	?j2?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
InputDialog
	"Enter Guest Count"
	"1"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{029}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j1"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTabNameKeyboard
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
{028}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"2"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{027}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
	"List of existing owned tables"
ExistingTables
	"2"
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{026}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"1"
	"2"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{025}
FloorPlanScreen*
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[3]
	[Open\Drawer]
	[6]
	[Get\Check]
InputDialog
	"Enter Guest Count"
	"1"
	[<]
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
{024}
TransferTableScreen
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK*]
	[Cancel]
TransferFromEmployees
	"Select employee to transfer from"
*
	"JEFFREY OYENEYE"
TransferTables
	"Select table you wish to transfer"
	"Select tab you wish to transfer"
	"j1"
ReceiveEmployees
	"Select employee to receive transfer"
*
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
{022}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"j1"
ExistingTables
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{021}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	"j1"
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{020}
TransferTableScreen
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK]
	[Cancel]
TransferFromEmployees
	"Select employee to transfer from"
*
	"JEFFREY OYENEYE"
TransferTables
	"Select table you wish to transfer"
	"Select tab you wish to transfer"
	"j1"
ReceiveEmployees
	"Select employee to receive transfer"
*
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
{018}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
ExistingTables
RightCommands
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
{017}
ReceiveTransfersScreen
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
ExistingTables
RightCommands
	[OK]
	[New Table]
	[Merge Table]
	[Cancel]
{016}
WWTScreen
	"MIGUEL"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{015}
ReceiveTransfersScreen
	"LEBRON JAMES"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
ExistingTables
RightCommands
	[OK]
	[New Table]
	[Merge Table]
	[Cancel]
{014}
ReceiveTransfersScreen
	"LEBRON JAMES"
	"Transfers"
	"List of incoming transfers"
IncomingTables
	"1"
ExistingTables
RightCommands
	[Cancel]
{013}
WWTScreen
	"LEBRON"
Tabs
	[btnSetTableEntry]
Tables
	"1"
TopRightButtons
	[Exit]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
EnterTableNumberNumpad
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
{012}
TransferTableScreen
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK]
	[Cancel]
TransferFromEmployees
	"Select employee to transfer from"
*
	"JEFFREY OYENEYE"
TransferTables
	"Select table you wish to transfer"
	"1"
	"Select tab you wish to transfer"
ReceiveEmployees
	"Select employee to receive transfer"
*
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
{011}
TransferTableScreen
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK*]
	[Cancel]
TransferFromEmployees
	"Select employee to transfer from"
*
	"JEFFREY OYENEYE"
TransferTables
	"Select table you wish to transfer"
	"1"
	"Select tab you wish to transfer"
ReceiveEmployees
	"Select employee to receive transfer"
*
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
{010}
SplitSeatScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"For Table"
CheckOrSeat
	"Seat 1"
	"COKE"
CheckOrSeat
	"Seat 2"
	"7 UP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split check]
	[Close]
{009}
WWTScreen
	"JEFFREY"
	[btnSetTabEntry]
Tabs
	[btnSetTableEntry]
Tables
TopRightButtons
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
EnterTabNameKeyboard
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
{008}
SplitSeatScreen
SplitScreen
	"Table 1"
CheckOrSeats
CheckOrSeat
	"For Table"
CheckOrSeat
	"Seat 1"
	"COKE"
	"7 UP"
	[<]
	[>]
BottomCenterButtons
	[Combine]
	[Add]
	[Split check]
	[Close]
{007}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
KeyboardEntryDialog
	"Enter special message"
	""
DialogSeparator
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[_]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
{006}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
Items
	" Large"
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
CenterModButtons
	[Sausage]
	[Pepperoni]
	[Onions]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{005}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" Chicken"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{004}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{003}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" Large"
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
{002}
PizzaModifierScreen
GroupOneButtons
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
GroupTwoButtons
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
ModCodeButtons
	[Add]
	[No]
AdditionalModGroupButtons
	[Pizza Toppings]
PizzaPortionButtons
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
Items
	" 1/2"
	" 1/2"
CenterModButtons
	[Cheese]
	[Chicken]
	[Beef]
BottomCenterButtons
	[OK]
	[Cancel]
BottomRightButtons
	[Delete]
	[btnMessage]
