State:576
/FloorPlanScreen*/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[1.2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[1.3]
	[Open\Drawer]
	[6]
	[Get\Check]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:575
/FloorPlanScreen/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[1.2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[1.3]
	[Open\Drawer]
	[6]
	[Get\Check]
State:558
/FloorPlanScreen/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[3]
	[Open\Drawer]
	[6]
	[Get\Check]
State:412
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
	"test"
/Items/
	" Large"
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:408
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" Beef"
	" Beef"
	" 1/2"
	" Chicken"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:407
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" Beef"
	" Beef"
	" 1/2"
	" Chicken"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You may not have more than 3 items from the Pizza Toppings group."
	[X]
	[OK]
State:406
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" Beef"
	" Beef"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:402
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:401
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Large"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:400
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:399
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" 1/2"
	" Chicken"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:398
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" Beef"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:397
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:396
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" Large"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:395
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Peperoni Pizza"
	"10.00"
/Items/
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:310
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
	[btnHideOrShowKeyboard]
/GetCheckDialog/
/TopCancelOkButtons/
	[btnClose]
	"Get Tab"
	[btnOk]
/TopGetButtons/
	[Get Table]
	[Get Tab]
	[Get Check]
	??
/Keyboard/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
State:298
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
/CheckOrSeat/
	"Check 2"
	"Seat 2"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:297
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
	"Seat 2"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:294
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat/
	"Seat 1"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
/CheckOrSeat/
	"Seat 2"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:284
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat/
	"Seat 1"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:275
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:274
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" Chicken"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:272
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You are required to enter between 1 and 3 item(s) from the Pizza Toppings mod group."
	[X]
	[OK]
State:270
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:268
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
/Items/
	" Large"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:265
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Cheese Pizza"
	"5.00"
/Items/
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:264
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Large"
	" Sausage"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You are required to enter exactly 1 item(s) from the Pizza Crust mod group."
	[X]
	[OK]
State:258
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Large"
	" Sausage"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:249
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE\ COKE"
	""
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/MessageDialog/
	"Modify Error"
/DialogSeparator/
	"Select an unordered item to modify before pressing the modify button."
	[X]
	[OK]
State:248
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"BBQ RIBS\ FULL RACK\ Baked Potato\ CUP"
	"41.94"
/Promos/
/Comps/
	"Sub Total"
	"41.94"
/Taxes/
	"Tax"
	"2.56"
	"Total"
	"44.50"
/Tenders/
	"Balance Due"
	"$44.50"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[MGR COMP]
	[OPEN $$]
	[EMP MEAL]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
/ItemSelectionDialog/
	"Select items to comp"
/DialogSeparator/
	^SELECT ALL^
	"SELECT ALL"
/Items_Container/
/Items/
	"Seat 1"
	^BBQ RIBS\ FULL RACK\ Baked Potato\ CUP^
	"BBQ RIBS\ FULL RACK\ Baked Potato\ CUP"
	"41.94"
	[Cancel]
	[OK*]
State:247
/FloorPlanScreen*/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[.21]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[.31]
	[Open\Drawer]
	[6]
	[Get\Check]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:246
/FloorPlanScreen/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[.21]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[.31]
	[Open\Drawer]
	[6]
	[Get\Check]
State:245
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat.2/
	"Seat 1"
	"COKE"
	"CORONA"
/CheckOrSeat.3/
	"Seat 2"
	"7 UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:244
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
/CheckOrSeat.2/
	"Check 2"
	"Seat 2"
	"7 UP"
/CheckOrSeat.3/
	"Check 3"
	"Seat 1"
	"COKE"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:243
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"COKE"
/CheckOrSeat.2/
	"Check 2"
	"Seat 2"
	"7 UP"
/CheckOrSeat.3/
	"Check 3"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:242
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
/CheckOrSeat.2/
	"Check 2"
	"Seat 2"
	"7 UP"
/CheckOrSeat.3/
	"Check 3"
	"Seat 1"
	"COKE"
	"CORONA"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:241
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"COKE"
	"CORONA"
/CheckOrSeat.2/
	"Check 2"
	"Seat 2"
	"7 UP"
/CheckOrSeat.3/
	"Check 3"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:240
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"COKE"
	"CORONA"
/CheckOrSeat.2/
	"Check 2"
	"Seat 2"
	"7 UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:239
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ NO FULL RACK\ Baked Potato\ CUP"
	"41.89"
/Promos/
/Comps/
	"Sub Total"
	"41.89"
/Taxes/
	"Tax"
	"2.56"
	"Total"
	"44.45"
/Tenders/
	"CASH"
	"44.45"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:238
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ NO FULL RACK\ Baked Potato\ CUP"
	"41.89"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:237
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - NO FULL RACK"
/Modifer.3/
	" - 1/2 RACK"
/Modifer.4/
	" - 1/2 RACK"
/Modifer.5/
	" - Baked Potato"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:236
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - NO FULL RACK"
/Modifer.3/
	" - 1/2 RACK"
/Modifer.4/
	" - 1/2 RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:235
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - NO FULL RACK"
/Modifer.3/
	" - 1/2 RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[1/2 RACK]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[*.15]
	[*.16]
	[*.17]
	[FULL RACK]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:234
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - NO FULL RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[1/2 RACK]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[*.15]
	[*.16]
	[*.17]
	[FULL RACK]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:233
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 5]
/ItemEntries/
	"Seat 5"
	"ICED TEA"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"CASH"
	"2.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:232
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 5]
/ItemEntries/
	"Seat 5"
	"ICED TEA"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"Balance Due"
	"$2.00"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:231
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 4]
/ItemEntries/
	"Seat 4"
	"DIET 7UP"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"CASH"
	"2.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:230
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 4]
/ItemEntries/
	"Seat 4"
	"DIET 7UP"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"Balance Due"
	"$2.00"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:229
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 3]
/ItemEntries/
	"Seat 3"
	"DIET COKE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"CASH"
	"2.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:228
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 3]
/ItemEntries/
	"Seat 3"
	"DIET COKE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"Balance Due"
	"$2.00"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:227
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 2]
/ItemEntries/
	"Seat 2"
	"COKE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"CASH"
	"2.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:226
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 2]
/ItemEntries/
	"Seat 2"
	"COKE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"Balance Due"
	"$2.00"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:225
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"WATER"
	"0.00"
/Promos/
/Comps/
	"Sub Total"
	"0.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"0.00"
/Tenders/
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:224
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat/
	"Seat 1"
	"Sausage Pizza\ Large\ Pan\ Sausage"
	"Veg 7 Thin\ Large\ Pan\ Cheese\ Chicken\ Beef\ VEGGIE\ CHEDDAR"
/CheckOrSeat/
	"Seat 2"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:223
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Platter\ Special canapes\  Vegetarian\  Vegan\ Ham Canapes"
	"0.00\3.50\\\1.00"
/Promos/
/Comps/
	"Sub Total"
	"4.50"
/Taxes/
	"Tax"
	"0.27"
	"Total"
	"4.77"
/Tenders/
	"CASH"
	"4.77"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:222
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"Platter\ Special canapes\  Vegetarian\  Vegan\ Ham Canapes"
	"0.00\3.50\\\1.00"
/Promos/
/Comps/
	"Sub Total"
	"4.50"
/Taxes/
	"Tax"
	"0.27"
	"Total"
	"4.77"
/Tenders/
	"Balance Due"
	"$4.77"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:221
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Platter\ Special canapes\  Vegetarian\  Vegan\ Ham Canapes"
	"0.00\3.50\\\1.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:220
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Platter"
	"0.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Platter"
	"(Optional modifiers, but no more than 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Platter"
	"0.00"
	" - Special canapes"
	" -  - Vegetarian"
	" -  - Vegan"
/CenterCategoryButtons/
	[Czech canapes]
	[Canapes]
	[Pickup]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Cheese Canapes]
	[Ham Canapes]
	[Fruit Canapes]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:219
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Platter"
	"0.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Platter"
	"(Optional modifiers, but no more than 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Special canapes"
/CenterCategoryButtons/
	[Vegetar/Vegan]
	[Pickup]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Vegetarian]
	[*]
	[Vegan]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:218
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"Platter\ Stand canapes\ Cheese Canapes"
	"0.00\2.50\1.00"
/Promos/
/Comps/
	"Sub Total"
	"3.50"
/Taxes/
	"Tax"
	"0.21"
	"Total"
	"3.71"
/Tenders/
	"CASH"
	"3.71"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:217
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"Platter\ Stand canapes\ Cheese Canapes"
	"0.00\2.50\1.00"
/Promos/
/Comps/
	"Sub Total"
	"3.50"
/Taxes/
	"Tax"
	"0.21"
	"Total"
	"3.71"
/Tenders/
	"Balance Due"
	"$3.71"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:216
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:215
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Platter\ Stand canapes\ Cheese Canapes"
	"0.00\2.50\1.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:214
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Platter"
	"0.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Platter"
	"(Optional modifiers, but no more than 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Platter"
	"0.00"
	" - Stand canapes"
/CenterCategoryButtons/
	[Czech canapes]
	[Canapes]
	[Pickup]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Cheese Canapes]
	[Ham Canapes]
	[Fruit Canapes]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:213
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Platter"
	"0.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Platter"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Platter"
	"0.00"
/CenterCategoryButtons/
	[Czech canapes]
	[Canapes]
	[Pickup]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Stand canapes]
	[Special canapes]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:212
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Table"
	"COKE"
	"2.00"
	"PORK NACHOS"
	"5.00"
/Promos/
/Comps/
	"Sub Total"
	"7.00"
/Taxes/
	"Tax"
	"0.31"
	"Total"
	"7.31"
/Tenders/
	"CASH"
	"7.31"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity*]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:211
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"COKE"
	"2.00"
	"PORK NACHOS"
	"5.00"
	"MILLER LITE"
	"3.00"
/Promos/
/Comps/
	"Sub Total"
	"10.00"
/Taxes/
	"Tax"
	"0.31"
	"Total"
	"10.31"
/Tenders/
	"CASH"
	"10.31"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:210
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"BBQ RIBS\ FULL RACK\ Baked Potato\ CUP"
	"41.94"
/Promos/
/Comps/
	"Sub Total"
	"41.94"
/Taxes/
	"Tax Exempt TEST"
	"0.00"
	"Total"
	"41.94"
/Tenders/
	"Balance Due"
	"$41.94"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:209
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"BBQ RIBS\ FULL RACK\ Baked Potato\ CUP"
	"41.94"
/Promos/
/Comps/
	"Sub Total"
	"41.94"
/Taxes/
	"Tax Exempt TEST"
	"0.00"
	"Total"
	"41.94"
/Tenders/
	"CASH"
	"41.94"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:208
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"COKE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"CASH"
	"2.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:207
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"H COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	[Hold]
	[Recipe]
	""
State:206
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"OPEN DESCR MOD"
	"10.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"ECARD"
	"$10 ECard"
	"PLU"
	"OPEN ITEM"
	"OPEN ITEM PRICE"
	"OPEN ITEM DES"
	"OPEN ITEM MOD"
	"OPEN PRICE MOD"
	"OPEN DESCR MOD"
	"OPEN FORCED MOD"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"TEST"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"TEST"
	"10.00"
/CenterCategoryButtons/
	[Open Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[OPEN ITEM]
	[OPEN ITEM PRICE]
	[OPEN ITEM DES]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
/KeyboardEntryDialog/
	"Enter description"
	""
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[_]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
State:205
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"OPEN DESCR MOD"
	"10.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"ECARD"
	"$10 ECard"
	"PLU"
	"OPEN ITEM"
	"OPEN ITEM PRICE"
	"OPEN ITEM DES"
	"OPEN ITEM MOD"
	"OPEN PRICE MOD"
	"OPEN DESCR MOD"
	"OPEN FORCED MOD"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"TEST"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"TEST"
	"10.00"
/CenterCategoryButtons/
	[Open Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[OPEN ITEM]
	[OPEN ITEM PRICE]
	[OPEN ITEM DES]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:204
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:203
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"OPEN PRICE MOD"
	"0.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"ECARD"
	"$10 ECard"
	"PLU"
	"OPEN ITEM"
	"OPEN ITEM PRICE"
	"OPEN ITEM DES"
	"OPEN ITEM MOD"
	"OPEN PRICE MOD"
	"OPEN DESCR MOD"
	"OPEN FORCED MOD"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"OPEN PRICE MOD"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"OPEN PRICE MOD"
	"2.00"
/CenterCategoryButtons/
	[Open Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[OPEN ITEM]
	[OPEN ITEM PRICE]
	[OPEN ITEM DES]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
/CurrencyInputDialog/
	"Enter price"
	"$"
	"0.00"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK*]
	[X]
State:202
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"OPEN PRICE MOD"
	"0.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"ECARD"
	"$10 ECard"
	"PLU"
	"OPEN ITEM"
	"OPEN ITEM PRICE"
	"OPEN ITEM DES"
	"OPEN ITEM MOD"
	"OPEN PRICE MOD"
	"OPEN DESCR MOD"
	"OPEN FORCED MOD"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"OPEN PRICE MOD"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"OPEN PRICE MOD"
	"2.00"
/CenterCategoryButtons/
	[Open Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[OPEN ITEM]
	[OPEN ITEM PRICE]
	[OPEN ITEM DES]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:201
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat*]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Table"
	"BBQ RIBS"
	"11.99"
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"BBQ RIBS"
	"11.99"
	" - FULL RACK"
	" - Baked Potato"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*]
	[HOUSE\SALAD]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[CAESAR\SALAD]
	[*]
	[BOWL]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:200
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat*]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Table"
	"BBQ RIBS"
	"11.99"
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"BBQ RIBS"
	"11.99"
	" - FULL RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[Black Beans]
	[*]
	[Red Beans]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:199
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat*]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Table"
	"BBQ RIBS"
	"11.99"
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"BBQ RIBS"
	"11.99"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[1/2 RACK]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[FULL RACK]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:198
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"3pcDrkBrstr"
	"9.99"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"3pcDrkBrstr"
	"(Optional unlimited modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"3pcDrkBrstr"
	"9.99"
	" - SP Bean C"
	" - Carrots"
	" - Cherry Bread"
/CenterCategoryButtons/
	[3C\Starter]
	[Farmhouse\Sd]
	[Breads]
	[3C\Dessert]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Fruit]
	[IceCreamVan Scp]
	[IceCreamChocScp]
	[Carml\Sundae]
	[Apple\Sundae]
	[Choc\Sundae]
	[Apple\Sundae]
	[ChocCn\Cookie]
	[*]
	[*]
	[ChocMM\Cookie]
	[*]
	[DblCrst\AplPie]
	[DblCrt\AplPiMd]
	[Coco\CrmPie]
	[*]
	[FrchChc\Pie]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:197
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"3pcDrkBrstr"
	"9.99"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"3pcDrkBrstr"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"3pcDrkBrstr"
	"9.99"
	" - SP Bean C"
	" - Carrots"
/CenterCategoryButtons/
	[3C\Starter]
	[Farmhouse\Sd]
	[Breads]
	[3C\Dessert]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[1 French Toast]
	[3 Hotcke Btrmlk]
	[3 Hotcke\Multi]
	[BanNut\Brd]
	[Biscuit]
	[Blue Bread]
	[Cherry\Bread]
	[Choc\Bread]
	[Ciabatta Bun]
	[Ciabatta Bun]
	[English\Muffin]
	[Fruit\Crepe]
	[Ginger\Bread]
	[Pmpkn\Bread]
	[Rolls]
	[Srdough\Toast]
	[Wheat Toast]
	[White\Toast]
	[*]
	[No\Bread]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:196
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"3pcDrkBrstr"
	"9.99"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"3pcDrkBrstr"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"3pcDrkBrstr"
	"9.99"
	" - SP Bean C"
/CenterCategoryButtons/
	[3C\Starter]
	[Farmhouse\Sd]
	[Breads]
	[3C\Dessert]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Garden Salad]
	[Apple Sauce]
	[Bk Potato]
	[Bk Swt Potat]
	[Broccoli]
	[Butter\Corn]
	[Carrots]
	[Cole\Slaw]
	[French Fries]
	[Fruit]
	[Green Beans]
	[Hash Brown]
	[Home Frie]
	[Mac Chz]
	[MashPot\Grv]
	[Onion Petals]
	[Dressing]
	[*]
	[*]
	[No Side]
	[*]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:195
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"3pcDrkBrstr"
	"9.99"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"3pcDrkBrstr"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"3pcDrkBrstr"
	"9.99"
/CenterCategoryButtons/
	[3C\Starter]
	[Farmhouse\Sd]
	[Breads]
	[3C\Dessert]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[*]
	[Garden Salad]
	[*]
	[*]
	[*]
	[*]
	[SP\Bean C]
	[SP\Bf Veggie C]
	[SP\Cz Potato C]
	[SP\Bean B]
	[SP\Bf Veggie B]
	[SP\Cz Potato B]
	[*]
	[*]
	[*]
	[SP\CkNoodles C]
	[SP\Brocc Cz C]
	[SP\Chili C]
	[SP\CkNoodles B]
	[SP\Brocc Cz B]
	[SP\Chili B]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:194
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Wrap"
	"5.50"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Wrap"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Pastries"
/CenterCategoryButtons/
	[ADD SOUR CRM]
	[BAGEL/CROISSANT]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[ON\BAGEL]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[ON\CROISSANT]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:193
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Wrap"
	"5.50"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Wrap"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Wrap"
	"5.50"
	" - 3 Bowl"
	" - NO Onion"
	" - Less Spicy"
/CenterCategoryButtons/
	[ADD BACON]
	[R.General MOD]
	[Mods A-F]
	[Desserts]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Milk Pudding]
	[Chocolate Ice]
	[*]
	[*]
	[*]
	[*]
	[Pastries]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:192
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Wrap"
	"5.50"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Wrap"
	"(Optional modifiers, but no more than 9 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Wrap"
	"5.50"
/CenterCategoryButtons/
	[ADD BACON]
	[R.General MOD]
	[Mods A-F]
	[Desserts]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Serve Now]
	[Serve LATER]
	[Rush this Item]
	[HOLD]
	[Hold ALL Items]
	[*]
	[1 Bowl]
	[2 Bowl]
	[3 Bowl]
	[No Spring Onion]
	[NO Sesame]
	[No Blend]
	[NO Onion]
	[No Garlic]
	[Dressing Aside]
	[No Spicy]
	[Less Spicy]
	[More Spicy]
	[*]
	[*]
	[*]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:191
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Classic"
	"11.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Classic"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Burrito Classic"
	"11.00"
	" - Verde"
/CenterCategoryButtons/
	[Burrito Rice]
	[Burrito Beans]
	[Burrito Meat]
	[Burrito Salsa]
	[Burrito Vege]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Tomato]
	[*]
	[Corn]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:190
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Classic"
	"11.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Classic"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"Burrito Classic"
	"11.00"
/CenterCategoryButtons/
	[Burrito Rice]
	[Burrito Beans]
	[Burrito Meat]
	[Burrito Salsa]
	[Burrito Vege]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Verde]
	[*]
	[Chipotle]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:189
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Persona"
	"11.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Persona"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Burrito Persona"
	"11.00"
/Modifer.2/
	" - Chili Rice"
/Modifer.3/
	" - Chili Rice"
/Modifer.4/
	" - White Beans"
/Modifer.5/
	" - Chicken"
/Modifer.6/
	" - Chicken"
/Modifer.7/
	" - Verde"
/CenterCategoryButtons/
	[Burrito Rice R]
	[Burrito Beans R]
	[Burrito Meat R]
	[Burrito Salsa R]
	[Burrito Vege R]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Tomato]
	[*]
	[Corn]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:188
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Persona"
	"11.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Persona"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Burrito Persona"
	"11.00"
/Modifer.2/
	" - Chili Rice"
/Modifer.3/
	" - Chili Rice"
/Modifer.4/
	" - White Beans"
/Modifer.5/
	" - Chicken"
/Modifer.6/
	" - Chicken"
/CenterCategoryButtons/
	[Burrito Rice R]
	[Burrito Beans R]
	[Burrito Meat R]
	[Burrito Salsa R]
	[Burrito Vege R]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Verde]
	[*]
	[Chipotle]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:187
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Persona"
	"11.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Persona"
	"(Optional modifiers, but no more than 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Burrito Persona"
	"11.00"
/Modifer.2/
	" - Chili Rice"
/Modifer.3/
	" - Chili Rice"
/Modifer.4/
	" - White Beans"
/CenterCategoryButtons/
	[Burrito Rice R]
	[Burrito Beans R]
	[Burrito Meat R]
	[Burrito Salsa R]
	[Burrito Vege R]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Chicken]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:186
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Persona"
	"11.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Persona"
	"(Optional modifiers, but no more than 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Burrito Persona"
	"11.00"
/Modifer.2/
	" - Chili Rice"
/Modifer.3/
	" - Chili Rice"
/CenterCategoryButtons/
	[Burrito Rice R]
	[Burrito Beans R]
	[Burrito Meat R]
	[Burrito Salsa R]
	[Burrito Vege R]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[White Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:185
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" CHEDDAR"
	" 1/2"
/CenterModButtons/
	[CHEDDAR]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:184
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Burrito Persona"
	"11.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Burrito Persona"
	"(Optional unlimited modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Burrito Persona"
	"11.00"
/CenterCategoryButtons/
	[Burrito Rice R]
	[Burrito Beans R]
	[Burrito Meat R]
	[Burrito Salsa R]
	[Burrito Vege R]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Chili Rice]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:183
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" CHEDDAR"
	" 1/2"
/CenterModButtons/
	[CHEDDAR]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You may not have more than 1 items from the CHEESE group."
	[X]
	[OK]
State:182
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Bread\ Garlic Spread"
	"1.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Bread"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Chive Spread"
/CenterCategoryButtons/
	[Spread Light T]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[BACON]
	[HAM]
	[CHORIZO]
	[CHEDDAR]
	[GOUDA]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[TOMATO]
	[MUSHROOM]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"At least 1 of Spread Light T is required"
	[X]
	[OK]
State:181
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Bread\ Garlic Spread"
	"1.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Bread"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Chive Spread"
/CenterCategoryButtons/
	[Spread Light T]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[BACON]
	[HAM]
	[CHORIZO]
	[CHEDDAR]
	[GOUDA]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[TOMATO]
	[MUSHROOM]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:180
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Bread\ Garlic Spread"
	"1.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Bread"
	"(Optional modifiers, but no more than 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Bread"
	"1.99"
/Modifer.2/
	" - Garlic Spread"
/CenterCategoryButtons/
	[Breads Spreads]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Garlic Spread]
	[*]
	[Chive Spread]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:179
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Bread"
	"1.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Bread"
	"(Optional unlimited modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Garlic Spread"
/CenterCategoryButtons/
	[Spread Toppings]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[BACON]
	[HAM]
	[CHORIZO]
	[CHEDDAR]
	[GOUDA]
	[*]
	[TOMATO]
	[MUSHROOM]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:178
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Bread"
	"1.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Bread"
	"(Optional modifiers, but no more than 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Bread"
	"1.99"
/CenterCategoryButtons/
	[Breads Spreads]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Garlic Spread]
	[*]
	[Chive Spread]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:177
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"RIBEYE\ BLACK & BLUE\ Baked Potato\ CAESAR SALAD\  ADD CHICKEN"
	"11.99\\\\3.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"RIBEYE"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"RIBEYE"
	"11.99"
/Modifer.2/
	" - BLACK & BLUE"
/Modifer.3/
	" - Baked Potato"
/Modifer.4/
	" - CAESAR SALAD"
/Modifer.5/
	" -  - ADD CHICKEN"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[BLACK & BLUE]
	[MEDIUM\WELL]
	[*]
	[MEDIUM]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[MED RARE]
	[*.14]
	[RARE]
	[WELL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:176
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"RIBEYE"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"RIBEYE"
	"(Optional modifiers, but no more than 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"CAESAR SALAD"
/CenterCategoryButtons/
	[ADD CHICKEN]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[ADD\CHICKEN]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:175
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"RIBEYE"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"RIBEYE"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"RIBEYE"
	"11.99"
/Modifer.2/
	" - BLACK & BLUE"
/Modifer.3/
	" - Baked Potato"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:174
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[CHEDDAR]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:173
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"RIBEYE"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"RIBEYE"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"RIBEYE"
	"11.99"
/Modifer.2/
	" - BLACK & BLUE"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:172
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"RIBEYE"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"RIBEYE"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"RIBEYE"
	"11.99"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[BLACK & BLUE]
	[MEDIUM\WELL]
	[*]
	[MEDIUM]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[MED RARE]
	[*.14]
	[RARE]
	[WELL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:171
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"PORK CHOP"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"PORK CHOP"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"PORK CHOP"
	"11.99"
/Modifer.2/
	" - BLACK & BLUE"
/Modifer.3/
	" - Baked Potato"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:170
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[VEGGIE]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:169
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"PORK CHOP"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"PORK CHOP"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"PORK CHOP"
	"11.99"
/Modifer.2/
	" - BLACK & BLUE"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:168
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Special Burger"
	"5.50"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"Mod Menu"
	"PORK\CHOP"
	"Special\Burger"
	"BBQ\RIBS"
	[Add Ice Mod]
	[Back to Menu]
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Special Burger"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Special Burger"
	"5.50"
/Modifer.2/
	" - BACON"
/CenterCategoryButtons/
	[Special Burger]
/RightPanelButtons/
	[Special\Message]
	[No]
	[Actual\Count]
	[+1]
	[Go to\Smart Beer]
	[MEDIUM]
	[WELL]
	[Clear\modifiers]
	[Extra]
	[RARE]
	[Clear\Count]
	[2]
	[BACON]
	""
	[ONION]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:167
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Special Burger"
	"5.50"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"Mod Menu"
	"PORK\CHOP"
	"Special\Burger"
	"BBQ\RIBS"
	[Add Ice Mod]
	[Back to Menu]
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Special Burger"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Special Burger"
	"5.50"
/Modifer.2/
	" - RARE"
/CenterCategoryButtons/
	[Special Burger]
/RightPanelButtons/
	[Special\Message]
	[No]
	[Actual\Count]
	[+1]
	[Go to\Smart Beer]
	[MEDIUM]
	[WELL]
	[Clear\modifiers]
	[Extra]
	[RARE]
	[Clear\Count]
	[2]
	[BACON]
	""
	[ONION]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:166
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"Special Burger"
	"5.50"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"Mod Menu"
	"PORK\CHOP"
	"Special\Burger"
	"BBQ\RIBS"
	[Add Ice Mod]
	[Back to Menu]
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"Special Burger"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"Special Burger"
	"5.50"
/CenterCategoryButtons/
	[Special Burger]
/RightPanelButtons/
	[Special\Message]
	[No]
	[Actual\Count]
	[+1]
	[Go to\Smart Beer]
	[MEDIUM]
	[WELL]
	[Clear\modifiers]
	[Extra]
	[RARE]
	[Clear\Count]
	[2]
	[BACON]
	""
	[ONION]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:165
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Optional modifiers, but no more than 10 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"COKE"
	"2.00"
	"test"
/CenterCategoryButtons/
	[Drink Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Ice]
	[*]
	[Sugar]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:164
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:163
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" VEGGIE"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[VEGGIE]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You may not have more than 1 items from the QUICHE group."
	[X]
	[OK]
State:162
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Optional modifiers, but no more than 10 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"COKE"
	"2.00"
/CenterCategoryButtons/
	[Drink Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Ice]
	[*]
	[Sugar]
/BottomLeftButtons/
	[btnKeyboard]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
/KeyboardEntryDialog/
	"Item Message"
	""
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[_]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
State:161
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[VEGGIE]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:160
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"PORK CHOP"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"PORK CHOP"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"PORK CHOP"
	"11.99"
/Modifer.2/
	" - MEDIUM"
/Modifer.3/
	" - Black Beans"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:159
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Optional modifiers, but no more than 10 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/Modifer.2/
	" - XT Ice"
/CenterCategoryButtons/
	[Drink Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Ice]
	[*]
	[Sugar]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:158
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:157
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Cheese"
	" Chicken"
	" Beef"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You may not have more than 3 items from the Pizza Toppings group."
	[X]
	[OK]
State:156
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:155
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Optional modifiers, but no more than 10 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/Modifer.2/
	" - NO Ice"
/CenterCategoryButtons/
	[Drink Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Ice]
	[*]
	[Sugar]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:154
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Optional modifiers, but no more than 10 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/CenterCategoryButtons/
	[Drink Mods]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Ice]
	[*]
	[Sugar]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:153
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"TENDERLN WRAPS\ Baked Potato"
	"5.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"SPN ARTCHK\DIP"
	"PORK\NACHOS"
	"HELLS\CHIPS"
	"QUESADILLA"
	"HUMMUS\APP"
	"FRIED MOZZ"
	"POTATO\CHIPS"
	"TENDERLN\WRAPS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"TENDERLN WRAPS"
	"(Choose special modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"TENDERLN WRAPS"
	"5.00"
/Modifer.2/
	" - Baked Potato"
/Modifer.3/
	" - ADD AVOCADO"
/CenterCategoryButtons/
	[STARCH]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[ADD\AVOCADO]
	[NO BREAD]
	[1/2 RACK]
	[WHITE]
	[FULL RACK]
	[RYE]
	[SWISS]
	[RASP\VIN]
	[CHEDDAR]
	[GOUDA]
	[BALSAMIC]
	[RANCH]
	[1000\ISLAND]
	[CAESAR]
	[NO\DRESSING]
	[BLUE\CHEESE]
	[WHEAT]
	[SOURDOUGH]
	[ENGLISH\MUFFIN]
	[ADD\SOUR CREAM]
	[*]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:152
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" Large"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:151
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
	[QUICHE]
	[CHEESE]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"VEG 7 THIN"
	"10.00"
/Items/
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:150
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"TENDERLN WRAPS\ Baked Potato"
	"5.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"SPN ARTCHK\DIP"
	"PORK\NACHOS"
	"HELLS\CHIPS"
	"QUESADILLA"
	"HUMMUS\APP"
	"FRIED MOZZ"
	"POTATO\CHIPS"
	"TENDERLN\WRAPS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"TENDERLN WRAPS"
	"(Choose special modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"TENDERLN WRAPS"
	"5.00"
/Modifer.2/
	" - Baked Potato"
/CenterCategoryButtons/
	[STARCH]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[ADD\AVOCADO]
	[NO BREAD]
	[1/2 RACK]
	[WHITE]
	[FULL RACK]
	[RYE]
	[SWISS]
	[RASP\VIN]
	[CHEDDAR]
	[GOUDA]
	[BALSAMIC]
	[RANCH]
	[1000\ISLAND]
	[CAESAR]
	[NO\DRESSING]
	[BLUE\CHEESE]
	[WHEAT]
	[SOURDOUGH]
	[ENGLISH\MUFFIN]
	[ADD\SOUR CREAM]
	[*]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:149
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"TENDERLN WRAPS\ Baked Potato"
	"5.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"SPN ARTCHK\DIP"
	"PORK\NACHOS"
	"HELLS\CHIPS"
	"QUESADILLA"
	"HUMMUS\APP"
	"FRIED MOZZ"
	"POTATO\CHIPS"
	"TENDERLN\WRAPS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"TENDERLN WRAPS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"TENDERLN WRAPS"
	"5.00"
/Modifer.2/
	" - Baked Potato"
/CenterCategoryButtons/
	[STARCH]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:148
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE\ COKE"
	""
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:147
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE\ COKE"
	""
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/Modifier_Container/
/Modifier/
	"COKE"
	"2.00"
	" - COKE"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*]
	[*]
	[ICED\COFFEE]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[*]
	[DIET COKE]
	[*]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnKeyboard*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:146
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE\ COKE\"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*.2]
	[*.3]
	[ICED\COFFEE]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[DIET COKE]
	[*.13]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnPrinter*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:145
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" Beef"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:144
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" Beef"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/MessageDialog/
	"Warning"
/DialogSeparator/
	"You may not have more than 3 items from the Pizza Toppings group."
	[X]
	[OK]
State:143
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE\ COKE\"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/Modifer.2/
	" - COKE"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*.2]
	[*.3]
	[ICED\COFFEE]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[DIET COKE]
	[*.13]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnPrinter*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:142
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"7 UP"
	"2.00"
	"COKE"
	"2.00.2"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/Modifer.2/
	" - COKE"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*.2]
	[*.3]
	[ICED\COFFEE]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[DIET COKE]
	[*.13]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnPrinter*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:141
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"7 UP"
	"2.00"
	"COKE"
	"2.00.2"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*.2]
	[*.3]
	[ICED\COFFEE]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[DIET COKE]
	[*.13]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnPrinter*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:140
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" Chicken"
	" Cheese"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:139
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/Modifer.2/
	" - COKE"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*.2]
	[*.3]
	[ICED\COFFEE]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[DIET COKE]
	[*.13]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnPrinter*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:138
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COKE"
	"(Please add between 1 and 99 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COKE"
	"2.00"
/CenterCategoryButtons/
	[Drink Refill]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[COKE]
	[ICED TEA]
	[*]
	[DIET 7UP]
	[*.2]
	[*.3]
	[ICED\COFFEE]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[DIET COKE]
	[*.13]
	[7 UP]
	[COFFEE]
/BottomLeftButtons/
	[btnPrinter*]
	[Delete Modifier]
	[Modify*]
	[Special*]
	[Cancel]
	[OK]
State:137
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"QUESADILLA"
	"5.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"SPN ARTCHK\DIP"
	"PORK\NACHOS"
	"HELLS\CHIPS"
	"QUESADILLA"
	"HUMMUS\APP"
	"FRIED MOZZ"
	"POTATO\CHIPS"
	"TENDERLN\WRAPS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"QUESADILLA"
	"(Optional unlimited modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"QUESADILLA"
	"5.00"
/Modifer.2/
	" - ADD AVOCADO"
/CenterCategoryButtons/
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[ADD\AVOCADO]
	[NO BREAD]
	[1/2 RACK]
	[WHITE]
	[FULL RACK]
	[RYE]
	[SWISS]
	[RASP\VIN]
	[CHEDDAR]
	[GOUDA]
	[BALSAMIC]
	[RANCH]
	[1000\ISLAND]
	[CAESAR]
	[NO\DRESSING]
	[BLUE\CHEESE]
	[WHEAT]
	[SOURDOUGH]
	[ENGLISH\MUFFIN]
	[ADD\SOUR CREAM]
	[*]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:136
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"PORK CHOP"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"PORK CHOP"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"PORK CHOP"
	"11.99"
/Modifer.2/
	" - MEDIUM"
/Modifer.3/
	" - Baked Potato"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:135
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"PORK CHOP"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"PORK CHOP"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"PORK CHOP"
	"11.99"
/Modifer.2/
	" - MEDIUM"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:134
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"PORK CHOP"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"PORK CHOP"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"PORK CHOP"
	"11.99"
/CenterCategoryButtons/
	[MEAT TEMP]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[BLACK & BLUE]
	[MEDIUM\WELL]
	[*]
	[MEDIUM]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[MED RARE]
	[*.14]
	[RARE]
	[WELL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:133
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - 1/2 RACK"
/Modifer.3/
	" - 1/2 RACK"
/Modifer.4/
	" - Baked Potato"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:132
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - 1/2 RACK"
/Modifer.3/
	" - 1/2 RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:131
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - 1/2 RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[1/2 RACK]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[*.15]
	[*.16]
	[*.17]
	[FULL RACK]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:130
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - FULL RACK"
/Modifer.3/
	" - Baked Potato"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[CUP]
	[*]
	[*.2]
	[HOUSE\SALAD]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[CAESAR\SALAD]
	[*.15]
	[BOWL]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:129
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/Modifer.2/
	" - FULL RACK"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Baked Potato]
	[*]
	[BUFFET]
	[No Starch]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Black Beans]
	[*.14]
	[Red Beans]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:128
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS"
	"11.99"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"BBQ RIBS"
	"(Please add between 1 and 2 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"BBQ RIBS"
	"11.99"
/CenterCategoryButtons/
	[RIBS]
	[STARCH]
	[SOUP MOD]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[1/2 RACK]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[*.15]
	[*.16]
	[*.17]
	[FULL RACK]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:127
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3\ TILAPIA\  FRIES\  PEPSI\ GRILLED CHCKEN\  FRIES\  PEPSI\ ROASTED CHCKEN\  FRIES\  PEPSI"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:126
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"ROASTED CHCKEN"
/Modifer.2/
	" - FRIES"
/CenterCategoryButtons/
	[Sides]
	[Drink Combo]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Fanta\Orange]
	[POWERADE]
	[*]
	[SWEET TEA]
	[*.2]
	[*.3]
	[PEPSI]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[Fanta\Strby]
	[*.13]
	[Fanta\Grape]
	[HI C ORANGE]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:125
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"ROASTED CHCKEN"
/CenterCategoryButtons/
	[Sides]
	[Drink Combo]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[FRIES]
	[Black Beans]
	[*]
	[Red Beans]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Baked Potato]
	[*.14]
	[SWT POT\FRIES]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:124
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 3 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COMBO 3"
	"10.00"
/Modifer.2/
	" - TILAPIA"
/Modifer.3/
	" -  - FRIES"
/Modifer.4/
	" -  - PEPSI"
/Modifer.5/
	" - GRILLED CHCKEN"
/Modifer.6/
	" -  - FRIES"
/Modifer.7/
	" -  - PEPSI"
/CenterCategoryButtons/
	[COMBO 3]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[TILAPIA]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[*.15]
	[GRILLED\CHCKEN]
	[*.16]
	[ROASTED\CHCKEN]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:123
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"GRILLED CHCKEN"
/Modifer.2/
	" - FRIES"
/CenterCategoryButtons/
	[Sides]
	[Drink Combo]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Fanta\Orange]
	[POWERADE]
	[*]
	[SWEET TEA]
	[*.2]
	[*.3]
	[PEPSI]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[Fanta\Strby]
	[*.13]
	[Fanta\Grape]
	[HI C ORANGE]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:122
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"GRILLED CHCKEN"
/CenterCategoryButtons/
	[Sides]
	[Drink Combo]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[FRIES]
	[Black Beans]
	[*]
	[Red Beans]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[Baked Potato]
	[*.14]
	[SWT POT\FRIES]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:121
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 3 modifiers)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"COMBO 3"
	"10.00"
/Modifer.2/
	" - TILAPIA"
/Modifer.3/
	" -  - FRIES"
/Modifer.4/
	" -  - PEPSI"
/CenterCategoryButtons/
	[COMBO 3]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[TILAPIA]
	[*]
	[*.2]
	[*.3]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[*.13]
	[*.14]
	[*.15]
	[GRILLED\CHCKEN]
	[*.16]
	[ROASTED\CHCKEN]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:120
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COMBO 3"
	"10.00"
/Seats/
	[T]
	[1]
	[>]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"COMBO 1"
	"COMBO 2"
	"COMBO 3"
	"Burger Combo"
	"Optional Mods"
	"Special Burger"
	"Burger & Side"
	"Quick Burger"
	"Warai Set (2)"
	"Wrap"
	"Burrito Classic"
	"Burrito Persona"
	"Bread"
	"Platter"
	"3pcDrkBrstr"
	"Pavels Meaty Bu"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ModifierScreen/
	"COMBO 3"
	"(Please add exactly 1 modifier)"
	[btnTopLeftCancel]
	[btnTopRightClose]
/ModifierItem_Container/
/ModifierItem/
/Modifer/
	"TILAPIA"
/Modifer.2/
	" - FRIES"
/CenterCategoryButtons/
	[Sides]
	[Drink Combo]
/RightPanelButtons/
/ModifierCodeButtons/
	[No]
	[Extra]
	[Side]
	[Half]
/RightModifierButtons/
	[Fanta\Orange]
	[POWERADE]
	[*]
	[SWEET TEA]
	[*.2]
	[*.3]
	[PEPSI]
	[*.4]
	[*.5]
	[*.6]
	[*.7]
	[*.8]
	[*.9]
	[*.10]
	[*.11]
	[*.12]
	[Fanta\Strby]
	[*.13]
	[Fanta\Grape]
	[HI C ORANGE]
/BottomLeftButtons/
	[btnPrinter]
	[Delete Modifier]
	[Modify]
	[Special]
	[Cancel]
	[OK]
State:119
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/InputDialog/
	"Enter table name"
	"0"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:118
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:117
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Table"
	"COKE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"2.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"2.00"
/Tenders/
	"CASH"
	"2.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity*]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:116
/ReceiveTransfersScreen/
	"LEBRON JAMES"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tables"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:115
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:114
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tabs"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:113
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	"j2"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:112
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
/EnterTabNameKeyboard/
	?j2?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:111
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"2"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:110
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
	"2"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:109
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:108
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
	"41.89"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:107
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
	[btnHideOrShowKeyboard]
/GetCheckDialog/
/TopCancelOkButtons/
	[btnClose]
	"Get Table"
	[btnOk]
/TopGetButtons/
	[Get Table]
	[Get Tab]
	[Get Check]
	??
/Keyboard/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
State:106
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
	[btnHideOrShowKeyboard]
State:105
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
	[btnHideOrShowKeyboard]
/GetCheckDialog/
/TopCancelOkButtons/
	[btnClose]
	"Get Table"
	[btnOk]
/TopGetButtons/
	[Get Table]
	[Get Tab]
	[Get Check]
	??
/Keyboard/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
State:104
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:103
/WWTScreen/
	"LEBRON"
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Ascending]
	[btnHideOrShowKeyboard]
State:102
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
	"7 UP"
	"2.00"
	"ICED COFFEE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:101
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat.2/
	"Seat 1"
	"COKE"
	"7 UP"
	"CORONA"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:100
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"ICED COFFEE"
	"2.00"
	"Seat 2"
	"COKE"
	"2.00"
	"7 UP"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"6.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"6.00"
/Tenders/
	"CASH"
	"6.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:099
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"ICED COFFEE"
	"2.00"
	"Seat 2"
	"COKE"
	"2.00"
	"7 UP"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"6.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"6.00"
/Tenders/
	"Balance Due"
	"$6.00"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:098
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"ICED COFFEE"
	"2.00"
	"Seat 2"
	"COKE"
	"2.00"
	"7 UP"
	"2.00"
/Seats/
	[T]
	[1]
	[2]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:097
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
	"HIGH LIFE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"10.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"10.00"
/Tenders/
	"CASH"
	"10.00"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:096
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tables"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/InputDialog/
	"Enter table name"
	"0"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:095
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
	"HIGH LIFE"
	"2.00"
/Promos/
/Comps/
	"Sub Total"
	"10.00"
/Taxes/
	"Tax"
	"0.00"
	"Total"
	"10.00"
/Tenders/
	"Balance Due"
	"$10.00"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:094
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
	"CHICKEN CAESAR"
	"3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:093
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:092
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
	"HIGH LIFE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:091
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
	"CORONA"
	"3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:090
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"MILLER LITE"
	"3.00"
	"BLUE MOON"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:089
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"MILLER LITE"
	"3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:088
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[SANDWICHES]
	[PIZZA]
	[BEER]
	[RETAIL]
	[Smart Beer]
	[Combos]
	[Burgers]
	[Chicken & Fish]
/MenuOrModButtons/
	"MILLER\LITE"
	"BLUE\MOON"
	"CORONA"
	"HIGH\LIFE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:087
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
	"CALI CHIX WRAP\ FRIES"
	"4.00"
/Promos/
/Comps/
	"Sub Total"
	"20.00"
/Taxes/
	"Tax"
	"1.22"
	"Total"
	"21.22"
/Tenders/
	"CASH"
	"21.22"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:086
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:085
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
	"CALI CHIX WRAP\ FRIES"
	"4.00"
/Promos/
/Comps/
	"Sub Total"
	"20.00"
/Taxes/
	"Tax"
	"1.22"
	"Total"
	"21.22"
/Tenders/
	"Balance Due"
	"$21.22"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:084
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
	"CALI CHIX WRAP\ FRIES"
	"4.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:083
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
	"CHIX SLD SAND\ FRIES"
	"4.00"
	"HAM SANDWICH\ FRIES"
	"4.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:082
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
	"CHIX SLD SAND\ FRIES"
	"4.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:081
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:080
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
	"VEGGIE WRAP\ FRIES"
	"4.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:079
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:078
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BUFF CHIX WRAP\ FRIES"
	"4.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:077
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"BUFF CHIX\WRAP"
	"VEGGIE\WRAP"
	"CHIX SLD\SAND"
	"HAM\SANDWICH"
	"CALI CHIX\WRAP"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:076
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
	"CHEESECAKE"
	"2.50"
/Promos/
/Comps/
	"Sub Total"
	"7.50"
/Taxes/
	"Tax"
	"0.46"
	"Total"
	"7.96"
/Tenders/
	"CASH"
	"7.96"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:075
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
	"CHEESECAKE"
	"2.50"
/Promos/
/Comps/
	"Sub Total"
	"7.50"
/Taxes/
	"Tax"
	"0.46"
	"Total"
	"7.96"
/Tenders/
	"Balance Due"
	"$7.96"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:074
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
	"CHEESECAKE"
	"2.50"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:073
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CARROT CAKE"
	"2.50"
	"CHOCOLATE CAKE"
	"2.50"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:072
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tables"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:071
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CARROT CAKE"
	"2.50"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:070
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CARROT\CAKE"
	"CHOCOLATE\CAKE"
	"CHEESECAKE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:069
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
	"CHICKEN CAESAR"
	"3.00"
	"SOUP OF DAY\ CUP"
	"3.00"
/Promos/
/Comps/
	"Sub Total"
	"21.00"
/Taxes/
	"Tax"
	"1.28"
	"Total"
	"22.28"
/Tenders/
	"CASH"
	"22.28"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:068
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
	"CHICKEN CAESAR"
	"3.00"
	"SOUP OF DAY\ CUP"
	"3.00"
/Promos/
/Comps/
	"Sub Total"
	"21.00"
/Taxes/
	"Tax"
	"1.28"
	"Total"
	"22.28"
/Tenders/
	"Balance Due"
	"$22.28"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
State:067
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"WATER"
/CheckOrSeat/
	"Check 2"
	"Seat 2"
	"COKE"
/CheckOrSeat/
	"Check 3"
	"Seat 3"
	"DIET COKE"
/CheckOrSeat/
	"Check 4"
	"Seat 4"
	"DIET 7UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:066
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 5"
	"Seat 5"
	"ICED TEA"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:065
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"WATER"
	"Seat 5"
	"ICED TEA"
/CheckOrSeat/
	"Check 2"
	"Seat 2"
	"COKE"
/CheckOrSeat/
	"Check 3"
	"Seat 3"
	"DIET COKE"
/CheckOrSeat/
	"Check 4"
	"Seat 4"
	"DIET 7UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:064
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"WATER"
	"Seat 4"
	"DIET 7UP"
	"Seat 5"
	"ICED TEA"
/CheckOrSeat/
	"Check 2"
	"Seat 2"
	"COKE"
/CheckOrSeat/
	"Check 3"
	"Seat 3"
	"DIET COKE"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:063
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"WATER"
	"Seat 3"
	"DIET COKE"
	"Seat 4"
	"DIET 7UP"
	"Seat 5"
	"ICED TEA"
/CheckOrSeat/
	"Check 2"
	"Seat 2"
	"COKE"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:062
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"WATER"
	"Seat 2"
	"COKE"
	"Seat 3"
	"DIET COKE"
	"Seat 4"
	"DIET 7UP"
	"Seat 5"
	"ICED TEA"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:061
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
/CheckOrSeat/
	"Check 2"
	"Seat 2"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:060
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
	"Seat 2"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:059
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat/
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
/CheckOrSeat/
	"Seat 2"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:058
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat/
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:057
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"COKE"
/CheckOrSeat.2/
	"Check 2"
	"Seat 2"
	"7 UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:056
/SplitCheckScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"Check 1"
	"Seat 1"
	"COKE"
	"Seat 2"
	"7 UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split seat]
	[Close]
State:055
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
/EnterTabNameKeyboard/
	?j1?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:054
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tables"
/ExistingTables/
	"2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/InputDialog/
	"Enter table name"
	"0"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:053
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat*]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"SJ 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:052
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
	"CHICKEN CAESAR"
	"3.00"
	"SOUP OF DAY\ CUP"
	"3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:051
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tables"
/ExistingTables/
	"2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/KeyboardEntryDialog/
	"Enter tab name"
	""
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
State:050
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tabs"
/ExistingTables/
	"j1"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:049
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
	"2"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:048
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
	"HOUSE SALAD\ RANCH\ ADD CHICKEN"
	"3.00\\3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:047
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tabs"
/ExistingTables/
	"j1"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:046
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:045
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTabNameKeyboard/
	?j1?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:044
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTabNameKeyboard/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
State:043
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"CHOPPED SALAD"
	"3.00"
	"CAESAR SALAD\ ADD CHICKEN"
	"3.00\3.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"CHOPPED\SALAD"
	"CAESAR\SALAD"
	"HOUSE\SALAD"
	"CHICKEN\CAESAR"
	"SOUP\OF DAY"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:042
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tabs"
/ExistingTables/
	"j2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/KeyboardEntryDialog/
	"Enter tab name"
	""
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
State:041
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tabs"
/ExistingTables/
	"j2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/InputDialog/
	"Enter table name"
	"0"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:040
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tabs"
/ExistingTables/
	"j2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:039
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j2"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:038
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
	[btnHideOrShowKeyboard]
State:037
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tabs"
/ExistingTables/
	"j2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:036
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Back]
/BottomRightButtons/
	[Show\Open Time]
	[Sorted by\Tab Names]
	[Sorted\Descending]
	[btnHideOrShowKeyboard]
State:035
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat.2/
	"Seat 1"
	"COKE"
	"7 UP"
	"ICED COFFEE"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:034
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"BBQ RIBS\ 1/2 RACK\ 1/2 RACK\ Baked Potato\ CUP"
	"41.89"
	"PORK CHOP\ MEDIUM\ Baked Potato\ CUP"
	"11.99"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"PORK\CHOP"
	"TILAPIA"
	"ROASTED\CHCKEN"
	"LASAGNA"
	"BBQ\RIBS"
	"LOBSTR\MAC CHZ"
	"RIBEYE"
	"BUFFET"
	"PORK\CHOP MODS"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
State:033
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"j1"
	"List of existing owned tables"
/ExistingTables/
	"2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:032
/TransferTableScreen/
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK*]
	[Cancel]
/TransferFromEmployees/
	"Select employee to transfer from"
	"JEFFREY OYENEYE"
/TransferTables/
	"Select table you wish to transfer"
	"Select tab you wish to transfer"
/ReceiveEmployees/
	"Select employee to receive transfer"
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
State:031
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
	"2"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:030
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:029
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
/EnterTabNameKeyboard/
	?j1?
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:028
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"2"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:027
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tables"
/ExistingTables/
	"2"
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:026
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j2"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
	[btnHideOrShowKeyboard]
State:025
/FloorPlanScreen*/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[3]
	[Open\Drawer]
	[6]
	[Get\Check]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
State:024
/TransferTableScreen/
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK*]
	[Cancel]
/TransferFromEmployees/
	"Select employee to transfer from"
	"JEFFREY OYENEYE"
/TransferTables/
	"Select table you wish to transfer"
	"Select tab you wish to transfer"
	"j1"
/ReceiveEmployees/
	"Select employee to receive transfer"
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
State:023
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ItemSelectionDialog/
	"Select items to void"
/DialogSeparator/
	^SELECT ALL^
	"SELECT ALL"
/Items_Container/
/Items/
	"Seat 1"
	^COKE^
	"COKE"
	"2.00"
	[Cancel]
	[OK]
State:022
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
/KeyboardEntryDialog/
	"Enter tab name"
	""
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
State:021
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	"j1"
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:020
/TransferTableScreen/
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK]
	[Cancel]
/TransferFromEmployees/
	"Select employee to transfer from"
	"JEFFREY OYENEYE"
/TransferTables/
	"Select table you wish to transfer"
	"Select tab you wish to transfer"
	"j1"
/ReceiveEmployees/
	"Select employee to receive transfer"
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
State:019
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
	[HERE]
	[TO GO]
	[DON'T MAKE]
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
	"Seat 1"
	"COKE"
	"2.00"
/Seats/
	[T]
	[1]
	[+]
/CenterMenuButtons/
	[LUNCH MENU]
	[DRINKS]
	[APPS]
	[ENTREES]
	[SOUP & SALADS]
	[DESSERT]
	[SANDWICHES]
	[PIZZA]
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/ItemSelectionDialog/
	"Select items to void"
/DialogSeparator/
	^SELECT ALL^
	"SELECT ALL"
/Items_Container/
/Items/
	"Seat 1"
	^COKE^
	"COKE"
	"2.00"
	[Cancel]
	[OK*]
State:018
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tables"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:017
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
	"List of existing owned tables"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[Merge Table]
	[Cancel]
State:016
/WWTScreen/
	"MIGUEL"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
	"1"
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Balance Inquiry*]
	[Back]
/EnterTableNumberNumpad/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[Ok]
	[btnHideOrShowKeyboard]
State:015
/ReceiveTransfersScreen/
	"LEBRON JAMES"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[Merge Table]
	[Cancel]
State:014
/ReceiveTransfersScreen/
	"LEBRON JAMES"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
/ExistingTables/
/RightCommands/
	[Cancel]
State:013
/ReceiveTransfersScreen/
	"MIGUEL SAAVEDRA"
	"Transfers"
	"List of incoming transfers"
/IncomingTables/
	"1"
/ExistingTables/
/RightCommands/
	[OK]
	[New Table]
	[New Tab]
	[Merge Table]
	[Merge Tab]
	[Cancel]
State:012
/TransferTableScreen/
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK]
	[Cancel]
/TransferFromEmployees/
	"Select employee to transfer from"
	"JEFFREY OYENEYE"
/TransferTables/
	"Select table you wish to transfer"
	"1"
	"Select tab you wish to transfer"
/ReceiveEmployees/
	"Select employee to receive transfer"
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
State:011
/TransferTableScreen/
	[btnWaiter]
	"JEFFREY OYENEYE"
	[OK*]
	[Cancel]
/TransferFromEmployees/
	"Select employee to transfer from"
	"JEFFREY OYENEYE"
/TransferTables/
	"Select table you wish to transfer"
	"1"
	"Select tab you wish to transfer"
/ReceiveEmployees/
	"Select employee to receive transfer"
	"LEBRON JAMES"
	"VLADIMIR PALOCKO"
	"JEFFREY OYENEYE"
	"MIGUEL SAAVEDRA"
	"JIRKA MALINA"
	"SAMEUL L. JACKSON"
State:010
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat.2/
	"Seat 1"
	"COKE"
/CheckOrSeat.3/
	"Seat 2"
	"7 UP"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:009
/WWTScreen/
	"JEFFREY"
	[btnSetTabEntry]
/Tabs/
	[btnSetTableEntry]
/Tables/
/TopRightButtons/
	[Exit]
	[Get Check]
	[Transfer Table]
	[Show Open Times]
	[Back]
/EnterTabNameKeyboard/
	??
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[/]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[*]
	[!]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok]
	[btnHideOrShowKeyboard]
State:008
/SplitSeatScreen/
/SplitScreen/
	"Table 1"
/CheckOrSeat/
	"For Table"
/CheckOrSeat.2/
	"Seat 1"
	"ICED COFFEE"
/CheckOrSeat.3/
	"Seat 2"
	"7 UP"
	"COKE"
	[<]
	[>]
/BottomCenterButtons/
	[Combine]
	[Add]
	[Split check]
	[Close]
State:007
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
/KeyboardEntryDialog/
	"Enter special message"
	""
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[0]
	[q]
	[w]
	[e]
	[r]
	[t]
	[y]
	[u]
	[i]
	[o]
	[p]
	[a]
	[s]
	[d]
	[f]
	[g]
	[h]
	[j]
	[k]
	[l]
	[z]
	[x]
	[c]
	[v]
	[b]
	[n]
	[m]
	[_]
	[Clear]
	[ ]
	[]
	[⌫]
	[Ok*]
	[X]
State:006
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"10.00"
/Items/
	" Large"
	" Pan"
	" Sausage"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Sausage]
	[Pepperoni]
	[Onions]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:005
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" Chicken"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:004
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" Large"
	" Pan"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:003
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" Large"
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:002
/PizzaModifierScreen/
/GroupOneButtons/
	"Pizza Size"
	[Small]
	[Medium]
	[Large]
/GroupTwoButtons/
	"Pizza Crust"
	[Thin]
	[Chicago Style]
	[Pan]
/ModCodeButtons/
	[Add]
	[No]
/AdditionalModGroupButtons/
	[Pizza Toppings]
/PizzaPortionButtons/
	[Whole]
	[Left]
	[Right]
	"Sausage Pizza"
	"5.00"
/Items/
	" 1/2"
	" 1/2"
/CenterModButtons/
	[Cheese]
	[Chicken]
	[Beef]
/BottomCenterButtons/
	[OK]
	[Cancel]
/BottomRightButtons/
	[Delete]
	[btnMessage]
State:001
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
	"Seat 1"
	"BUFFET (0.75 llbs)"
	"3.00"
/Promos/
/Comps/
	"Sub Total"
	"3.00"
/Taxes/
	"Tax"
	"0.18"
	"Total"
	"3.18"
/Tenders/
	"CASH"
	"3.18"
	"Change"
	"$0.00"
/MidButtons/
	[Gift Card Balance]
	[Close]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
