/{558}/
/FloorPlanScreen/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[3]
	[Open\Drawer]
	[6]
	[Get\Check]
/{303}/
/TenderScreen/
/TopRightButtons/
	[Tables]
	[Order]
	[Print]
	[Email/SMS]
	[Exit]
/TopLeftButtons/
	[Payment]
	[Get Mobile Pay Code*]
	[Promo]
	[Comp]
	"Table 1"
	[Check 1]
/ItemEntries/
/*/
	"Seat 1"
	"COKE"
	"2.00"
	"PORK NACHOS"
	"5.00"
	"MILLER LITE"
	"3.00"
/Promos/
/Comps/
	"Sub Total"
	"10.00"
/Taxes/
	"Tax"
	"0.31"
	"Total"
	"10.31"
/Tenders/
	"Balance Due"
	"$10.31"
/MidButtons/
	[Gift Card Balance]
	[Close*]
/MidLeftButtons/
	[CASH]
	[ECARD]
	[Euro]
	[Exact]
	[House Acc]
	[Euro Round]
	[$10]
/BottomRightButtons/
	[Delete]
/BottomLeftButtons/
	[Loyalty]
	[Add Gratuity]
	[Tax Exempt]
/WarningBarControl/
	"Card payments not available (Status: Payment Service Disconnected or Not Found)"
/{281}/
/OrderScreen/
/TopLeftButtons/
	[btnGoToFloorplan]
	[Split Check]
	[Split Seat]
	[Done]
/TopRightButtons/
/TableAndChecks/
	"Table 1"
	[Clear]
	[Check 1]
	[+]
/EntriesBySeat/
/*/
/Seats/
	[+]
/CenterMenuButtons/
/MenuOrModButtons/
	"FRIED MOZZ"
	"Quick Menu"
	[Mod Menu\Items]
	"MILLER\LITE"
	"CORONA"
	"7 UP"
	"BLUE\MOON"
	"PORK\NACHOS"
	"SPN ARTCHK\DIP"
	"COKE"
	[Scripts Test\Panel]
	[Pizza Menu]
	"ICED\COFFEE"
/BottomButtons/
	[$]
	[Scan Barcode]
	[Select Printer]
	[Transfer]
	[Void]
	[Loyalty]
	[Quantity]
	[Repeat]
	[Modify]
	[Delete]
	""
/{025}/
/FloorPlanScreen*/
	[7]
	[WWT\Screen]
	[1]
	[Exit]
	[5]
	[4]
	[Detach\Tables]
	[2]
	[Combine\Tables]
	[Adjust\Tips]
	[8]
	[BAR]
	[3]
	[Open\Drawer]
	[6]
	[Get\Check]
/InputDialog/
	"Enter Guest Count"
	"1"
	[<]
/DialogSeparator/
	[1]
	[2]
	[3]
	[4]
	[5]
	[6]
	[7]
	[8]
	[9]
	[Clear]
	[0]
	[OK]
	[X]
